package main

import (
	"database/sql"
	"log"
	"os"

	_ "github.com/lib/pq"
)

func main() {
	connectionString := getConnectionString()

	dbConnection, err := sql.Open("postgres", connectionString)
	if err != nil {
		log.Fatal(err)
	}

	// Test connection to database
	err = dbConnection.Ping()
	if err != nil {
		log.Fatal(err)
	}

	defer dbConnection.Close()

	createTable(dbConnection)
}

func getConnectionString() string {
	bytes, err := os.ReadFile("../secrets/connectionString.txt")
	if err != nil {
		log.Fatal()
	}
	return string(bytes)
}

func createTable(dbConnection *sql.DB) {
	query := `CREATE TABLE IF NOT EXISTS products (
		id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		name VARCHAR(50) NOT NULL
	)`

	_, err := dbConnection.Exec(query)
	if err != nil {
		log.Fatal()
	}
}

type Product struct {
	Id   int
	Name string
}

func insertProduct(dbConnection *sql.DB, product *Product) int {
	// Variable for the primary key to be returned from the database
	var id int
	// Make a query that inserts a product and returns the generated id
	query := `INSERT INTO product (name) VALUES($1) RETURNING id`
	// Execute the query and scan the id
	err := dbConnection.QueryRow(query, product.Name).Scan(&id)
	if err != nil {
		log.Fatal(err)
	}
	return id
}
