package main

import (
	"database/sql"
	"fmt"
	"log"
	"os"

	_ "github.com/lib/pq"
)

func main() {
	connectionString := getConnectionString()

	dbConnection, err := sql.Open("postgres", connectionString)
	if err != nil {
		log.Fatal(err)
	}

	// Test connection to database
	err = dbConnection.Ping()
	if err != nil {
		log.Fatal(err)
	}

	defer dbConnection.Close()

	createTable(dbConnection)

	var product1 Product = Product{Name: "Alice"}
	var product2 Product = Product{Name: "Bob"}
	var product3 Product = Product{Name: "Carl"}
	var product4 Product = Product{Name: "Daniel"}
	var products []Product = []Product{product1, product2, product3, product4}

	var ids []int = []int{}

	for i := 0; i < len(products); i++ {
		ids = append(ids, insertProduct(dbConnection, &products[i]))
		fmt.Printf("Id = %v\n", ids[i])
	}

	// Get the products back from the database
	var prodPtr *Product
	fmt.Println("Getting products from the database...")
	for i := 0; i < len(ids); i++ {
		prodPtr = getProduct(dbConnection, ids[i])
		fmt.Println(*prodPtr)
	}
}

func getConnectionString() string {
	bytes, err := os.ReadFile("../secrets/connectionString.txt")
	if err != nil {
		log.Fatal()
	}
	return string(bytes)
}

func createTable(dbConnection *sql.DB) {
	query := `CREATE TABLE IF NOT EXISTS products (
		id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		name VARCHAR(50) NOT NULL
	)`

	_, err := dbConnection.Exec(query)
	if err != nil {
		log.Fatal()
	}
}

type Product struct {
	Id   int
	Name string
}

func insertProduct(dbConnection *sql.DB, product *Product) int {
	// Variable for the primary key to be returned from the database
	var id int
	// Make a query that inserts a product and returns the generated id
	query := `INSERT INTO products (name) VALUES($1) RETURNING id`
	// Execute the query and scan the id
	err := dbConnection.QueryRow(query, product.Name).Scan(&id)
	if err != nil {
		log.Fatal(err)
	}
	return id
}

// Returning a pointer to a local struct would be unsafe in C/C++,
// but it is safe in go.
func getProduct(dbConnection *sql.DB, id int) *Product {
	var product Product
	query := `SELECT name FROM products WHERE id=$1`
	err := dbConnection.QueryRow(query, id).Scan(&product.Name)
	if err != nil {
		if err == sql.ErrNoRows {
			log.Fatalf("No row found with Id = %v\n", id)
		}
		log.Fatal()
	}
	product.Id = id
	return &product
}
